use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = manifest_dir.join("../..");
    let tables_dir = root.join("config/tables");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("tables.rs");

    for file in ["cars.tsv", "jobs.tsv", "loot.tsv"] {
        println!("cargo:rerun-if-changed={}", tables_dir.join(file).display());
    }

    let mut code = String::new();
    code.push_str("// @generated by crates/ddd_core/build.rs\n\n");
    code.push_str(&generate_cars(&tables_dir.join("cars.tsv")));
    code.push_str(&generate_jobs(&tables_dir.join("jobs.tsv")));
    let loot_items = loot_items(&tables_dir.join("loot.tsv"));
    code.push_str(&generate_black_market_parts(&loot_items));
    code.push_str(&generate_primary_loot(&loot_items));
    code.push_str(&generate_bonus_loot(&loot_items));

    fs::write(out_file, code).unwrap();
}

fn generate_cars(path: &Path) -> String {
    let rows = read_tsv(path);
    let mut code = String::new();
    code.push_str("pub fn starter_car_catalog() -> Vec<crate::car::Car> {\n");
    code.push_str("    vec![\n");
    for row in rows
        .iter()
        .filter(|row| bool_value(v(row, "starter_eligible")))
    {
        code.push_str("        ");
        code.push_str(&car_expr(row));
        code.push_str(",\n");
    }
    code.push_str("    ]\n}\n\n");

    code.push_str("pub fn market_car_catalog() -> Vec<crate::car::Car> {\n");
    code.push_str("    vec![\n");
    for row in rows
        .iter()
        .filter(|row| bool_value(v(row, "market_eligible")))
    {
        code.push_str("        ");
        code.push_str(&car_expr(row));
        code.push_str(",\n");
    }
    code.push_str("    ]\n}\n\n");

    code.push_str("pub(crate) fn starter_cars() -> Vec<crate::car::Car> {\n");
    code.push_str("    starter_car_catalog()\n");
    code.push_str("}\n\n");

    for row in &rows {
        code.push_str(&format!(
            "#[allow(dead_code)]\npub(crate) fn car_{}() -> crate::car::Car {{\n    {}\n}}\n\n",
            ident(v(row, "id")),
            car_expr(row)
        ));
    }
    code
}

fn generate_jobs(path: &Path) -> String {
    let rows = read_tsv(path);
    let mut code = String::new();
    code.push_str("pub fn starter_jobs() -> Vec<crate::job::Job> {\n");
    code.push_str("    vec![\n");
    for row in &rows {
        code.push_str(&format!(
            "        crate::job::Job::new({}, crate::job::CargoType::{}, crate::job::Terrain::{}, {}, {}, {}, {}),\n",
            str_lit(v(row, "name")),
            cargo(v(row, "cargo")),
            terrain(v(row, "terrain")),
            v(row, "cargo_size"),
            v(row, "payout"),
            v(row, "heat"),
            v(row, "distance"),
        ));
    }
    code.push_str("    ]\n}\n\n");
    code
}

fn generate_black_market_parts(items: &BTreeMap<String, BTreeMap<String, String>>) -> String {
    let mut code = String::new();
    code.push_str("pub(crate) fn black_market_upgrade_catalog() -> Vec<crate::loot::LootItem> {\n");
    code.push_str("    vec![\n");
    for row in items
        .values()
        .filter(|row| bool_value(v(row, "black_market_eligible")))
    {
        code.push_str("        ");
        code.push_str(&loot_item_expr(row));
        code.push_str(",\n");
    }
    code.push_str("    ]\n}\n\n");
    code
}

fn generate_primary_loot(items: &BTreeMap<String, BTreeMap<String, String>>) -> String {
    let mut by_cargo: BTreeMap<String, Vec<BTreeMap<String, String>>> = BTreeMap::new();
    for row in items
        .values()
        .filter(|row| !v(row, "primary_cargo").is_empty())
    {
        by_cargo
            .entry(v(row, "primary_cargo").to_string())
            .or_default()
            .push(row.clone());
    }

    let mut code = String::new();
    code.push_str(
        "pub(crate) fn primary_loot(job: &crate::job::Job, roll: u8) -> crate::loot::LootItem {\n",
    );
    code.push_str("    match job.cargo {\n");
    for (cargo_name, rows) in by_cargo {
        code.push_str(&format!(
            "        crate::job::CargoType::{} => match roll {{\n",
            cargo(&cargo_name)
        ));
        for row in rows {
            code.push_str(&format!(
                "            {}..={} => {},\n",
                v(&row, "primary_min_roll"),
                v(&row, "primary_max_roll"),
                loot_item_expr(&row)
            ));
        }
        code.push_str("            _ => unreachable!(\"primary loot roll outside 0..=99\"),\n");
        code.push_str("        },\n");
    }
    code.push_str("    }\n}\n\n");
    code
}

fn generate_bonus_loot(items: &BTreeMap<String, BTreeMap<String, String>>) -> String {
    let mut code = String::new();
    code.push_str(
        "pub(crate) fn bonus_loot(job: &crate::job::Job, roll: u8) -> crate::loot::LootItem {\n",
    );
    code.push_str("    match roll {\n");
    for row in items
        .values()
        .filter(|row| !v(row, "bonus_min_roll").is_empty())
    {
        let value_expr = format!(
            "{} + job.terrain.roughness() as i32 * {}",
            v(row, "value"),
            v(row, "value_per_roughness")
        );
        code.push_str(&format!(
            "        {}..={} => {},\n",
            v(row, "bonus_min_roll"),
            v(row, "bonus_max_roll"),
            loot_item_expr_with_value(row, &value_expr)
        ));
    }
    code.push_str("        _ => unreachable!(\"bonus loot roll outside 0..=99\"),\n");
    code.push_str("    }\n}\n\n");
    code
}

fn car_expr(row: &BTreeMap<String, String>) -> String {
    format!(
        "crate::car::Car::new({}, {}, crate::loot::LootRarity::{}, {}, {}, {}, {}, crate::car::Drivetrain::{}, crate::car::VehicleSpec {{ make: {}.to_string(), model: {}.to_string(), trim: {}.to_string(), body_style: {}.to_string(), transmission: {}.to_string(), curb_weight_lbs: {}, cargo_volume_cu_ft: {}.to_string(), fuel_capacity_gal: {}.to_string(), engine: crate::car::EngineSpec {{ layout: {}.to_string(), displacement_liters: {}.to_string(), aspiration: {}.to_string(), fuel: {}.to_string(), horsepower: {}, horsepower_rpm: {}, torque_lb_ft: {}, torque_rpm: {} }} }})",
        str_lit(v(row, "name")),
        str_lit(v(row, "flavor")),
        rarity(v(row, "rarity")),
        v(row, "model_year"),
        v(row, "value"),
        v(row, "cargo_capacity"),
        v(row, "stealth"),
        drivetrain(v(row, "drivetrain")),
        str_lit(v(row, "make")),
        str_lit(v(row, "model")),
        str_lit(v(row, "trim")),
        str_lit(v(row, "body_style")),
        str_lit(v(row, "transmission")),
        v(row, "curb_weight_lbs"),
        str_lit(v(row, "cargo_volume_cu_ft")),
        str_lit(v(row, "fuel_capacity_gal")),
        str_lit(v(row, "engine_layout")),
        str_lit(v(row, "displacement_liters")),
        str_lit(v(row, "aspiration")),
        str_lit(v(row, "fuel")),
        v(row, "horsepower"),
        v(row, "horsepower_rpm"),
        v(row, "torque_lb_ft"),
        v(row, "torque_rpm"),
    )
}

fn loot_item_expr(row: &BTreeMap<String, String>) -> String {
    loot_item_expr_with_value(row, v(row, "value"))
}

fn loot_item_expr_with_value(row: &BTreeMap<String, String>, value_expr: &str) -> String {
    format!(
        "crate::loot::LootItem {{ name: {}.to_string(), rarity: crate::loot::LootRarity::{}, black_market_value: {}, effect: {} }}",
        str_lit(v(row, "name")),
        rarity(v(row, "rarity")),
        value_expr,
        loot_effect_expr(row),
    )
}

fn loot_effect_expr(row: &BTreeMap<String, String>) -> String {
    match v(row, "effect") {
        "SellOnly" => "crate::loot::LootEffect::SellOnly".to_string(),
        "VehicleUpgrade" => format!(
            "crate::loot::LootEffect::VehicleUpgrade(crate::loot::UpgradeEffect {{ stealth_modifier: {}, drivetrain_modifier: {}, repair_discount_percent: {}, install_cost: {} }})",
            v(row, "stealth_modifier"),
            v(row, "drivetrain_modifier"),
            v(row, "repair_discount_percent"),
            v(row, "install_cost"),
        ),
        "InstallCostVoucher" => format!(
            "crate::loot::LootEffect::InstallCostVoucher(crate::loot::InstallCostVoucherEffect {{ discount_percent: {} }})",
            v(row, "discount_percent"),
        ),
        other => panic!("unknown loot effect {other}"),
    }
}

fn read_tsv(path: &Path) -> Vec<BTreeMap<String, String>> {
    let text = fs::read_to_string(path).unwrap();
    let mut lines = text.lines().filter(|line| !line.trim().is_empty());
    let headers: Vec<String> = lines
        .next()
        .unwrap_or_else(|| panic!("{} is empty", path.display()))
        .split('\t')
        .map(str::to_string)
        .collect();

    lines
        .enumerate()
        .map(|(index, line)| {
            let values: Vec<String> = line.split('\t').map(str::to_string).collect();
            if values.len() != headers.len() {
                panic!(
                    "{}:{} has {} columns, expected {}",
                    path.display(),
                    index + 2,
                    values.len(),
                    headers.len()
                );
            }
            headers
                .iter()
                .cloned()
                .zip(values)
                .collect::<BTreeMap<_, _>>()
        })
        .collect()
}

fn loot_items(path: &Path) -> BTreeMap<String, BTreeMap<String, String>> {
    read_tsv(path)
        .into_iter()
        .map(|row| (v(&row, "id").to_string(), row))
        .collect()
}

fn v<'a>(row: &'a BTreeMap<String, String>, key: &str) -> &'a str {
    row.get(key)
        .unwrap_or_else(|| panic!("missing column {key}"))
        .as_str()
}

fn bool_value(value: &str) -> bool {
    match value {
        "true" => true,
        "false" => false,
        other => panic!("unknown boolean value {other}"),
    }
}

fn str_lit(value: &str) -> String {
    format!("{value:?}")
}

fn ident(value: &str) -> String {
    value
        .chars()
        .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
        .collect()
}

fn cargo(value: &str) -> &'static str {
    match value {
        "Documents" => "Documents",
        "Parts" => "Parts",
        "Contraband" => "Contraband",
        other => panic!("unknown cargo type {other}"),
    }
}

fn terrain(value: &str) -> &'static str {
    match value {
        "City" => "City",
        "Industrial" => "Industrial",
        "Rural" => "Rural",
        "Mountain" => "Mountain",
        other => panic!("unknown terrain {other}"),
    }
}

fn drivetrain(value: &str) -> &'static str {
    match value {
        "Fwd" => "Fwd",
        "Rwd" => "Rwd",
        "Awd" => "Awd",
        "FourWd" => "FourWd",
        other => panic!("unknown drivetrain {other}"),
    }
}

fn rarity(value: &str) -> &'static str {
    match value {
        "Common" => "Common",
        "Uncommon" => "Uncommon",
        "Rare" => "Rare",
        other => panic!("unknown rarity {other}"),
    }
}
