#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BalanceConfig {
    pub chance_min: u8,
    pub chance_max: u8,
    pub cargo_too_large_heat: u8,
    pub breakdown_condition_threshold: u8,
    pub breakdown_payout_divisor: i32,
    pub breakdown_heat: u8,
    pub patrol_close_call_heat: u8,
    pub patrol_detection_job_heat_multiplier: u8,
    pub patrol_blend_base: i16,
    pub patrol_blend_stealth_multiplier: i16,
    pub patrol_blend_job_heat_multiplier: i16,
    pub patrol_blend_garage_heat_multiplier: i16,
    pub patrol_blend_cargo_size_multiplier: i16,
    pub patrol_blend_failure_heat: u8,
    pub patrol_detour_base: i16,
    pub patrol_detour_terrain_multiplier: i16,
    pub patrol_detour_condition_divisor: i16,
    pub patrol_detour_garage_heat_multiplier: i16,
    pub patrol_detour_failure_suspension_extra: u8,
    pub patrol_detour_failure_tires_extra: u8,
    pub patrol_push_base: i16,
    pub patrol_push_horsepower_divisor: i16,
    pub patrol_push_condition_divisor: i16,
    pub patrol_push_terrain_multiplier: i16,
    pub patrol_push_job_heat_multiplier: i16,
    pub patrol_push_garage_heat_multiplier: i16,
    pub patrol_push_failure_heat: u8,
    pub patrol_push_failure_engine_damage: u8,
    pub patrol_push_failure_tire_damage: u8,
    pub fork_highway_base: i16,
    pub fork_highway_stealth_multiplier: i16,
    pub fork_highway_job_heat_multiplier: i16,
    pub fork_highway_garage_heat_multiplier: i16,
    pub fork_highway_cargo_size_multiplier: i16,
    pub fork_highway_failure_heat: u8,
    pub fork_service_base: i16,
    pub fork_service_terrain_multiplier: i16,
    pub fork_service_condition_divisor: i16,
    pub fork_service_garage_heat_multiplier: i16,
    pub fork_service_failure_suspension_extra: u8,
    pub fork_service_failure_tires_extra: u8,
    pub fork_service_failure_body_damage: u8,
    pub fork_backtrack_payout_multiplier_percent: u8,
    pub segment_terrain_stress_multiplier: u8,
    pub segment_rough_terrain_2wd_penalty: u8,
    pub segment_low_condition_threshold: u8,
    pub segment_low_condition_penalty: u8,
    pub segment_stress_cap: u8,
    pub damage_tire_extra: u8,
    pub damage_suspension_extra: u8,
    pub damage_body_extra: u8,
    pub loot_base_drop_chance: u8,
    pub loot_job_heat_multiplier: u8,
    pub loot_cargo_size_multiplier: u8,
    pub loot_max_drop_chance: u8,
    pub loot_bonus_drop_chance: u8,
    pub black_market_min_parts: u8,
    pub black_market_max_parts: u8,
    pub black_market_common_weight: u8,
    pub black_market_uncommon_weight: u8,
    pub black_market_rare_weight: u8,
    pub black_market_common_markup_percent: u16,
    pub black_market_uncommon_markup_percent: u16,
    pub black_market_rare_markup_percent: u16,
    pub car_market_min_cars: u8,
    pub car_market_max_cars: u8,
    pub car_market_common_weight: u8,
    pub car_market_uncommon_weight: u8,
    pub car_market_rare_weight: u8,
    pub car_market_common_markup_percent: u16,
    pub car_market_uncommon_markup_percent: u16,
    pub car_market_rare_markup_percent: u16,
}

impl Default for BalanceConfig {
    fn default() -> Self {
        Self {
            chance_min: 10,
            chance_max: 90,
            cargo_too_large_heat: 1,
            breakdown_condition_threshold: 25,
            breakdown_payout_divisor: 4,
            breakdown_heat: 1,
            patrol_close_call_heat: 1,
            patrol_detection_job_heat_multiplier: 8,
            patrol_blend_base: 45,
            patrol_blend_stealth_multiplier: 5,
            patrol_blend_job_heat_multiplier: 6,
            patrol_blend_garage_heat_multiplier: 4,
            patrol_blend_cargo_size_multiplier: 3,
            patrol_blend_failure_heat: 2,
            patrol_detour_base: 65,
            patrol_detour_terrain_multiplier: 3,
            patrol_detour_condition_divisor: 8,
            patrol_detour_garage_heat_multiplier: 2,
            patrol_detour_failure_suspension_extra: 6,
            patrol_detour_failure_tires_extra: 3,
            patrol_push_base: 35,
            patrol_push_horsepower_divisor: 10,
            patrol_push_condition_divisor: 5,
            patrol_push_terrain_multiplier: 2,
            patrol_push_job_heat_multiplier: 3,
            patrol_push_garage_heat_multiplier: 3,
            patrol_push_failure_heat: 1,
            patrol_push_failure_engine_damage: 10,
            patrol_push_failure_tire_damage: 12,
            fork_highway_base: 55,
            fork_highway_stealth_multiplier: 4,
            fork_highway_job_heat_multiplier: 7,
            fork_highway_garage_heat_multiplier: 5,
            fork_highway_cargo_size_multiplier: 4,
            fork_highway_failure_heat: 2,
            fork_service_base: 70,
            fork_service_terrain_multiplier: 4,
            fork_service_condition_divisor: 8,
            fork_service_garage_heat_multiplier: 1,
            fork_service_failure_suspension_extra: 8,
            fork_service_failure_tires_extra: 5,
            fork_service_failure_body_damage: 2,
            fork_backtrack_payout_multiplier_percent: 80,
            segment_terrain_stress_multiplier: 5,
            segment_rough_terrain_2wd_penalty: 18,
            segment_low_condition_threshold: 60,
            segment_low_condition_penalty: 12,
            segment_stress_cap: 85,
            damage_tire_extra: 2,
            damage_suspension_extra: 3,
            damage_body_extra: 1,
            loot_base_drop_chance: 25,
            loot_job_heat_multiplier: 6,
            loot_cargo_size_multiplier: 4,
            loot_max_drop_chance: 75,
            loot_bonus_drop_chance: 30,
            black_market_min_parts: 2,
            black_market_max_parts: 3,
            black_market_common_weight: 62,
            black_market_uncommon_weight: 30,
            black_market_rare_weight: 8,
            black_market_common_markup_percent: 150,
            black_market_uncommon_markup_percent: 175,
            black_market_rare_markup_percent: 220,
            car_market_min_cars: 2,
            car_market_max_cars: 3,
            car_market_common_weight: 62,
            car_market_uncommon_weight: 30,
            car_market_rare_weight: 8,
            car_market_common_markup_percent: 130,
            car_market_uncommon_markup_percent: 150,
            car_market_rare_markup_percent: 180,
        }
    }
}
